[package]
name = "standard-payment-stored"
version = "0.1.0"
authors = ["Henry Till <henrytill@gmail.com>", "Ed Hastings <ed@casperlabs.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]
bench = false
doctest = false
test = false

[features]
default = []
std = ["contract-ffi/std"]

[dependencies]
contract-ffi = { path = "../../../contract-ffi", package = "casperlabs-contract-ffi" }
standard-payment = { path = "../standard-payment", default-features = false, features = ["lib"] }
